Phoenix
PhoenixPLvsPW
PhoenixSOJSD
PhoenixAAI
Apollo 
ApolloDD
ApolloSOJ
AthenaSOJ
Athena2D
Mia
Grossberg 
Diego
Yew
Gregory 
GregoryAAI
Raymond
Ryuunosuke
RyuunosukeBadgeless
Asougi
Ryuutarou
Hugh Def
Bonny Def Famme
Vincenzo
Payne
Gaspen
Auchi
Payne3D
Payne Train
Miles
MilesDD
EdgeworthSOJ
Manfred
Franziska
Godot
Klavier
KlavierDD
Portsman
Sebastian
Blaise
LaytonPLvsPW
Zacharias
Darklaw
Blackquill
BlackquillSOJ 
Nahyuta
Inga
Garan
AsougiPro
Barok
Disciple
Flynch
ApolloPro
Betty Pro Famme
Trucy Pro
Hawk
Neil
Mysterious Stranger
Zero
Brisbane
Vulper
Maya
MayaSOJ
MayaPLvsAA
Ema
Maggey 
Kristoph
HoboPhoenix
HoboTrucy
Trucy
Trucy Young
Byrne
Kay
Susato
Judge
JudgeBro
JudgeDGSNG
JudgeDGSAP
Seishirou
Stronghart
JudgeKhura'in
JudgeSOJ
Rayfa
Courtney
Hemlock
Abigail
Anna
Bongo
Burley
Vilen
Richard
Shiv
Maiday
Parker
Altamont
Evie
Merlin
Cop Juror
Charles
Gumshoe
Marshall 
Atmey
EmaSOJSD
Buddy
Badd 
Lang
Bobby
Herlock
Tobias
Gina
Snow
Renwick
Arme
Togamera
Cabanela 
Butz 
Sahwit
April
Bellboy
White 
Will
Oldbag
Cody
Penny
Sal
Vasquez 
Lotta 
Yanni
Polly
Lana
Angel 
Gant
Meekins
Wellington
Grey
Ini
Pearl
Morgan
Hotti 
Max
Moe
Ben
Regina
Acro 
Matt
deKiller
Adrian
Feenie
Dahlia
Ron
Desiree
Kudo
Armstrong
Furio
Viola
Lisa 
Fawles
Iris
Elise
Olga
Zak
Wocky Kitaki
Wesley
Alita
Guy
Plum
Winfred
Machi
LeTouse
Lamiroir
Daryan
Valant
Vera 
Vera Young
Drew
Spark
Rhoda Teneiro
Zinc
Cammy
Ernest 
Lance
Shiha
Lauren
WillP AAI
Colias
Alba
Huang
Nicole
Knightley
Simon
Elbird
Roland
Dogen
Jeffrey
Gustavia
Katherine Hall
Delicia
Bonnie and Karin
John Marsh
Greisen
Morag
Freude
Yossarian
Rhea
Espella
Petter
Old Rootie
Foxy
Cooper
Hoot
Smiles
Cracker
Shakey
Ridelle
Jean
Juniper
Tonate
Tenma
Filch
Jinxie
Florent 
Means
Newman
Hugh
Scuttlebutt
Starbuck 
Cosmos
Aura 
Ponco
Clonco
Orla
Buckler
Deplume
Crab
Ahlbi
Amara
Andistandhin
Bailiff
TrucySOJ
Betty
Bonny
Retinz
Datz
Geiru
Uendo
Atishon
PearlSOJ
Tahrust
Dhurke
Ellen
ButzSOJ
Armie
Sorin
Pierce
Bucky
Hosonaga
Jezaille
Mikotoba
Yuujin Mikotoba Suit
Nikolina
Strogenov
McGilded
Beppo
Furst
Iris Wilson 
Bruce
Joan
Garrideb
Maurice
Souseki
Pop
Nash
Ringo
Graydon
Rei
William
Roly
Patricia
Rumba
Tusspells
Drebber
Adron
Daley
Menimemo
Maria
Sithe 
Nosa
Venus
Gossip
Gotts
Olive
Harebrayne
Sailor 
BailiffDGS
Narrator
NarratorDGS
Psychelocks
Mood_Matrix
The Typewriter
Layton
Luke
Alfendi
Makepeace
Lucy
Anton
Chelmey
Claire
Clive
Descole
Don
Emmy
Flora
Grosky
Dimitri
Barton
Riddleton
Puzzlette
Katrielle Layton
Sissel
Lynne
iniswap1
iniswap2
iniswap3
iniswap4
iniswap5
iniswap6
iniswap7
iniswap8
iniswap9
iniswap10
iniswap11
iniswap12
iniswap13
iniswap14
iniswap15
iniswap16
iniswap17
iniswap18
iniswap19
iniswap20